// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[tool].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/EncoderDecoder.tsx";
import * as $$1 from "./islands/FormatValidate.tsx";
import * as $$2 from "./islands/Menu.tsx";
import * as $$3 from "./islands/PasswordGenerator.tsx";
import * as $$4 from "./islands/TextDiff.tsx";

const manifest = {
  routes: {
    "./routes/[tool].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/about.tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/EncoderDecoder.tsx": $$0,
    "./islands/FormatValidate.tsx": $$1,
    "./islands/Menu.tsx": $$2,
    "./islands/PasswordGenerator.tsx": $$3,
    "./islands/TextDiff.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
